public class FuncoesAritmeticas {
    public static void main(String[] args) {
        double numero;
        
        Scanner sc = new Scanner(System.in);
        double numero1 = Math.sqrt(25);
        double numero2 = Math.sqrt(numero);
        double potencia = Math.pow(2, 3);
        double arredondado = Math.round(4.7);
        double maximo = Math.max = (10, 20);
        double minimo = Math.min = (10, 20);
        double aleatorio = math.random();
        double pi = Math.PI;


        sc.close();
    }
}
